-- MySQL Script generated by MySQL Workbench
-- Wed 29 May 2019 20:47:59 EEST
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema eCommerce
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema eCommerce
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `eCommerce` DEFAULT CHARACTER SET utf8 ;
USE `eCommerce` ;

-- -----------------------------------------------------
-- Table `eCommerce`.`User`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCommerce`.`User` (
  `Username` VARCHAR(12) NOT NULL,
  `Password` VARCHAR(16) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `Surname` VARCHAR(45) NOT NULL,
  `Email` VARCHAR(45) NOT NULL,
  `Telephone` VARCHAR(20) NOT NULL,
  `Address` VARCHAR(128) NOT NULL,
  `GeoLocation` VARCHAR(45) NULL,
  `AFM` DECIMAL(10,0) NOT NULL,
  `Rating` VARCHAR(45) NULL,
  PRIMARY KEY (`Username`),
  UNIQUE INDEX `Username_UNIQUE` (`Username` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCommerce`.`Item`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCommerce`.`Item` (
  `ID` INT NOT NULL,
  `Seller_ID` VARCHAR(12) NOT NULL,
  `Name` VARCHAR(45) NOT NULL,
  `CurrentPrice` FLOAT NULL,
  `FirstBid` FLOAT NULL,
  `Num_of_bids` INT NULL DEFAULT 0,
  `Location` VARCHAR(45) NULL,
  `Country` VARCHAR(45) NULL,
  `Start_Date` DATETIME NULL,
  `End_Date` DATETIME NULL,
  `Description` VARCHAR(256) NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Item_User1_idx` (`Seller_ID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_Item_User1`
    FOREIGN KEY (`Seller_ID`)
    REFERENCES `eCommerce`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCommerce`.`Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCommerce`.`Category` (
  `Name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`Name`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCommerce`.`Item_has_Category`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCommerce`.`Item_has_Category` (
  `Item_ID` INT NOT NULL,
  `Category_Name` VARCHAR(256) NOT NULL,
  PRIMARY KEY (`Item_ID`, `Category_Name`),
  INDEX `fk_Item_has_Category_Category1_idx` (`Category_Name` ASC),
  INDEX `fk_Item_has_Category_Item_idx` (`Item_ID` ASC),
  CONSTRAINT `fk_Item_has_Category_Item`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `eCommerce`.`Item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Item_has_Category_Category1`
    FOREIGN KEY (`Category_Name`)
    REFERENCES `eCommerce`.`Category` (`Name`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCommerce`.`Images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCommerce`.`Images` (
  `Item_ID` INT NOT NULL,
  `ID` INT NOT NULL,
  `Image` BLOB NOT NULL,
  PRIMARY KEY (`ID`),
  INDEX `fk_Images_Item1_idx` (`Item_ID` ASC),
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC),
  CONSTRAINT `fk_Images_Item1`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `eCommerce`.`Item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCommerce`.`Bids`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCommerce`.`Bids` (
  `Item_ID` INT NOT NULL,
  `Bidder_ID` VARCHAR(12) NOT NULL,
  `DateTime` DATETIME NOT NULL,
  `Amount` FLOAT NOT NULL,
  PRIMARY KEY (`Item_ID`, `Bidder_ID`, `DateTime`),
  INDEX `fk_Bids_Item1_idx` (`Item_ID` ASC),
  INDEX `fk_Bids_User1_idx` (`Bidder_ID` ASC),
  CONSTRAINT `fk_Bids_Item1`
    FOREIGN KEY (`Item_ID`)
    REFERENCES `eCommerce`.`Item` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Bids_User1`
    FOREIGN KEY (`Bidder_ID`)
    REFERENCES `eCommerce`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `eCommerce`.`Messages`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `eCommerce`.`Messages` (
  `From_UserID` VARCHAR(12) NOT NULL,
  `To_UserID` VARCHAR(12) NOT NULL,
  `ID` INT NOT NULL,
  `DateTime` DATETIME NULL,
  `Message` VARCHAR(256) NULL,
  `Seen` TINYINT(1) NULL,
  PRIMARY KEY (`From_UserID`, `To_UserID`, `ID`),
  INDEX `fk_User_has_User_User2_idx` (`To_UserID` ASC),
  INDEX `fk_User_has_User_User1_idx` (`From_UserID` ASC),
  CONSTRAINT `fk_User_has_User_User1`
    FOREIGN KEY (`From_UserID`)
    REFERENCES `eCommerce`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_User_has_User_User2`
    FOREIGN KEY (`To_UserID`)
    REFERENCES `eCommerce`.`User` (`Username`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
